changes in buildspec.yml

diff --git a/copilot/pipelines/shs-fe-dev/buildspec.yml b/copilot/pipelines/shs-fe-dev/buildspec.yml
--- a/copilot/pipelines/shs-fe-dev/buildspec.yml
+++ b/copilot/pipelines/shs-fe-dev/buildspec.yml
@@ -48,15 +48,15 @@ phases:
       # (https://docs.docker.com/engine/reference/commandline/tag/)
       # Check if the `svc package` commanded exited with a non-zero status. If so, echo error msg and exit.
       - >
-        for env in $pl_envs; do
-          tag=$(echo ${CODEBUILD_BUILD_ID##*:}-$env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)
-          for svc in $svcs; do
-          ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
-          if [ $? -ne 0 ]; then
-            echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
-            exit 1;
-          fi
-          done;
+        # for env in $pl_envs; do
+        #   tag=$(echo ${CODEBUILD_BUILD_ID##*:}-$env | sed 's/:/-/g' | rev | cut -c 1-128 | rev)
+        #   for svc in $svcs; do
+        #   ./copilot-linux svc package -n $svc -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
+        #   if [ $? -ne 0 ]; then
+        #     echo "Cloudformation stack and config files were not generated. Please check build logs to see if there was a manifest validation error." 1>&2;
+        #     exit 1;
+        #   fi
+        #   done;
           for job in $jobs; do
           ./copilot-linux job package -n $job -e $env --output-dir './infrastructure' --tag $tag --upload-assets;
           if [ $? -ne 0 ]; then
